const List = [
  {
    id: 1,
    name: "BMW",
    images: [
      {
        id:19,
        url:"image/BMW/19.jpg"
        },
        {
        id:18,
        url:"image/BMW/18.jpg"
        },
        {
        id:17,
        url:"image/BMW/17.jpg"
        },
        {
        id:16,
        url:"image/BMW/16.jpg"
        },
        {
        id:15,
        url:"image/BMW/15.jpg"
        },
        {
        id:14,
        url:"image/BMW/14.jpg"
        },
        {
        id:13,
        url:"image/BMW/13.jpg"
        },
        {
        id:12,
        url:"image/BMW/12.jpg"
        },
        {
        id:11,
        url:"image/BMW/11.jpg"
        },
        {
        id:10,
        url:"image/BMW/10.jpg"
        },
        {
        id:9,
        url:"image/BMW/9.jpg"
        },
        {
        id:8,
        url:"image/BMW/8.jpg"
        },
        {
        id:7,
        url:"image/BMW/7.jpg"
        },
        {
        id:6,
        url:"image/BMW/6.jpg"
        },
        {
        id:5,
        url:"image/BMW/5.jpg"
        },
        {
        id:4,
        url:"image/BMW/4.jpg"
        },
        {
        id:3,
        url:"image/BMW/3.jpg"
        },
        {
        id:2,
        url:"image/BMW/2.jpg"
        },
        {
        id:1,
        url:"image/BMW/1.jpg"
        },
        
    ],
  },
  {
    id: 2,
    name: "TATA",
    images: [
      {
        id:18,
        url:"image/TATA/18.jpg"
        },
        {
        id:17,
        url:"image/TATA/17.jpg"
        },
        {
        id:16,
        url:"image/TATA/16.jpg"
        },
        {
        id:15,
        url:"image/TATA/15.jpg"
        },
        {
        id:14,
        url:"image/TATA/14.jpg"
        },
        {
        id:13,
        url:"image/TATA/13.jpg"
        },
        {
        id:12,
        url:"image/TATA/12.jpg"
        },
        {
        id:11,
        url:"image/TATA/11.jpg"
        },
        {
        id:10,
        url:"image/TATA/10.jpg"
        },
        {
        id:9,
        url:"image/TATA/9.jpg"
        },
        {
        id:8,
        url:"image/TATA/8.jpg"
        },
        {
        id:7,
        url:"image/TATA/7.jpg"
        },
        {
        id:6,
        url:"image/TATA/6.jpg"
        },
        {
        id:5,
        url:"image/TATA/5.jpg"
        },
        {
        id:4,
        url:"image/TATA/4.jpg"
        },
        {
        id:3,
        url:"image/TATA/3.jpg"
        },
        {
        id:2,
        url:"image/TATA/2.jpg"
        },
        {
        id:1,
        url:"image/TATA/1.jpg"
        },
        
    ],
  },
  {
    id: 3,
    name: "MERCEDES",
    images: [
      {
        id:27,
        url:"image/MERCEDES/27.jpg"
        },
        {
        id:26,
        url:"image/MERCEDES/26.jpg"
        },
        {
        id:25,
        url:"image/MERCEDES/25.jpg"
        },
        {
        id:24,
        url:"image/MERCEDES/24.jpg"
        },
        {
        id:23,
        url:"image/MERCEDES/23.jpg"
        },
        {
        id:22,
        url:"image/MERCEDES/22.jpg"
        },
        {
        id:21,
        url:"image/MERCEDES/21.jpg"
        },
        {
        id:20,
        url:"image/MERCEDES/20.jpg"
        },
        {
        id:19,
        url:"image/MERCEDES/19.jpg"
        },
        {
        id:18,
        url:"image/MERCEDES/18.jpg"
        },
        {
        id:17,
        url:"image/MERCEDES/17.jpg"
        },
        {
        id:16,
        url:"image/MERCEDES/16.jpg"
        },
        {
        id:15,
        url:"image/MERCEDES/15.jpg"
        },
        {
        id:14,
        url:"image/MERCEDES/14.jpg"
        },
        {
        id:13,
        url:"image/MERCEDES/13.jpg"
        },
        {
        id:12,
        url:"image/MERCEDES/12.jpg"
        },
        {
        id:11,
        url:"image/MERCEDES/11.jpg"
        },
        {
        id:10,
        url:"image/MERCEDES/10.jpg"
        },
        {
        id:9,
        url:"image/MERCEDES/9.jpg"
        },
        {
        id:8,
        url:"image/MERCEDES/8.jpg"
        },
        {
        id:7,
        url:"image/MERCEDES/7.jpg"
        },
        {
        id:6,
        url:"image/MERCEDES/6.jpg"
        },
        {
        id:5,
        url:"image/MERCEDES/5.jpg"
        },
        {
        id:4,
        url:"image/MERCEDES/4.jpg"
        },
        {
        id:3,
        url:"image/MERCEDES/3.jpg"
        },
        {
        id:2,
        url:"image/MERCEDES/2.jpg"
        },
        {
        id:1,
        url:"image/MERCEDES/1.jpg"
        },
        
    ],
  },
  {
    id: 4,
    name: "MAHINDRA",
    images: [
      {
        id:18,
        url:"image/MAHINDRA/18.jpg"
        },
        {
        id:17,
        url:"image/MAHINDRA/17.jpg"
        },
        {
        id:16,
        url:"image/MAHINDRA/16.jpg"
        },
        {
        id:15,
        url:"image/MAHINDRA/15.jpg"
        },
        {
        id:14,
        url:"image/MAHINDRA/14.jpg"
        },
        {
        id:13,
        url:"image/MAHINDRA/13.jpg"
        },
        {
        id:12,
        url:"image/MAHINDRA/12.jpg"
        },
        {
        id:11,
        url:"image/MAHINDRA/11.jpg"
        },
        {
        id:10,
        url:"image/MAHINDRA/10.jpg"
        },
        {
        id:9,
        url:"image/MAHINDRA/9.jpg"
        },
        {
        id:8,
        url:"image/MAHINDRA/8.jpg"
        },
        {
        id:7,
        url:"image/MAHINDRA/7.jpg"
        },
        {
        id:6,
        url:"image/MAHINDRA/6.jpg"
        },
        {
        id:5,
        url:"image/MAHINDRA/5.jpg"
        },
        {
        id:4,
        url:"image/MAHINDRA/4.jpg"
        },
        {
        id:3,
        url:"image/MAHINDRA/3.jpg"
        },
        {
        id:2,
        url:"image/MAHINDRA/2.jpg"
        },
        {
        id:1,
        url:"image/MAHINDRA/1.jpg"
        },
        
    ],
  },
  {
    id: 5,
    name: "VOLKSWAGEN",
    images: [
      {
        id:20,
        url:"image/VOLKSWAGEN/20.jpg"
        },
        {
        id:19,
        url:"image/VOLKSWAGEN/19.jpg"
        },
        {
        id:18,
        url:"image/VOLKSWAGEN/18.jpg"
        },
        {
        id:17,
        url:"image/VOLKSWAGEN/17.jpg"
        },
        {
        id:16,
        url:"image/VOLKSWAGEN/16.jpg"
        },
        {
        id:15,
        url:"image/VOLKSWAGEN/15.jpg"
        },
        {
        id:14,
        url:"image/VOLKSWAGEN/14.jpg"
        },
        {
        id:13,
        url:"image/VOLKSWAGEN/13.jpg"
        },
        {
        id:12,
        url:"image/VOLKSWAGEN/12.jpg"
        },
        {
        id:11,
        url:"image/VOLKSWAGEN/11.jpg"
        },
        {
        id:10,
        url:"image/VOLKSWAGEN/10.jpg"
        },
        {
        id:9,
        url:"image/VOLKSWAGEN/9.jpg"
        },
        {
        id:8,
        url:"image/VOLKSWAGEN/8.jpg"
        },
        {
        id:7,
        url:"image/VOLKSWAGEN/7.jpg"
        },
        {
        id:6,
        url:"image/VOLKSWAGEN/6.jpg"
        },
        {
        id:5,
        url:"image/VOLKSWAGEN/5.jpg"
        },
        {
        id:4,
        url:"image/VOLKSWAGEN/4.jpg"
        },
        {
        id:3,
        url:"image/VOLKSWAGEN/3.jpg"
        },
        {
        id:2,
        url:"image/VOLKSWAGEN/2.jpg"
        },
        {
        id:1,
        url:"image/VOLKSWAGEN/1.jpg"
        },
        
    ],
  },
  {
    id: 6,
    name: "FERRARI",
    images: [
      
        {
        id:18,
        url:"image/FERRARI/18.jpg"
        },
        {
        id:17,
        url:"image/FERRARI/17.jpg"
        },
        {
        id:16,
        url:"image/FERRARI/16.jpg"
        },
        {
        id:15,
        url:"image/FERRARI/15.jpg"
        },
        {
        id:14,
        url:"image/FERRARI/14.jpg"
        },
        {
        id:13,
        url:"image/FERRARI/13.jpg"
        },
        {
        id:12,
        url:"image/FERRARI/12.jpg"
        },
        {
        id:11,
        url:"image/FERRARI/11.jpg"
        },
        {
        id:10,
        url:"image/FERRARI/10.jpg"
        },
        {
        id:9,
        url:"image/FERRARI/9.jpg"
        },
        {
        id:8,
        url:"image/FERRARI/8.jpg"
        },
        {
        id:7,
        url:"image/FERRARI/7.jpg"
        },
        {
        id:6,
        url:"image/FERRARI/6.jpg"
        },
        {
        id:5,
        url:"image/FERRARI/5.jpg"
        },
        {
        id:4,
        url:"image/FERRARI/4.jpg"
        },
        {
        id:3,
        url:"image/FERRARI/3.jpg"
        },
        {
        id:2,
        url:"image/FERRARI/2.jpg"
        },
        {
        id:1,
        url:"image/FERRARI/1.jpg"
        },
        
    ],
  },
  
];

export default List;
